import "server-only";
import { NextResponse } from "next/server";
import { requireAuth, getUserPlan } from "@/lib/server-auth";
import {
  loadTasks,
  createTask,
  updateTask,
  setTaskDone,
  deleteTaskById,
  countUserTasks,
  countUserLooseTasks
} from "@/lib/storage";
import {
  countActiveSeries,
  ensureOccurrences,
  insertSeries,
  loadSeriesOccurrences,
  seriesStore
} from "@/lib/series-storage";
import {
  deleteFollowing,
  deleteOnlyThis,
  editFollowing,
  MAX_SERIES_PER_USER,
  type FollowingResult,
  type OccurrenceChanges
} from "@/lib/series";
import { ruleFromRepeat } from "@/lib/recurrence";
import { getTodayInTimeZone } from "@/lib/task-date";
import { parseScope, parseTaskPayload } from "@/lib/task-validation";
import { resolveUserTimeZone } from "@/lib/user-settings";
import { MAX_TASKS_PER_USER } from "@/lib/usage-limits";

const FREE_TASK_LIMIT = 15;

const unauthorized = () => NextResponse.json({ error: "Unauthorized" }, { status: 401 });

function followingFailure(result: Extract<FollowingResult, { ok: false }>) {
  return result.reason === "not_pending"
    ? NextResponse.json({ error: "Only a pending occurrence can be cut" }, { status: 409 })
    : NextResponse.json({ error: "Task not found" }, { status: 404 });
}

// GET /api/tasks?tz=<IANA zone> — load all tasks
//
// Before loading, brings the user's recurring series up to date: skips the
// occurrences that fell behind and creates the ones missing from today to
// today + 14 days. "Today" is the user's, not the server's, so the timezone the
// browser reports is stored and used here.
export async function GET(request: Request) {
  let userId: string;
  try { userId = await requireAuth(); }
  catch { return unauthorized(); }

  try {
    const { searchParams } = new URL(request.url);
    const timeZone = await resolveUserTimeZone(userId, searchParams.get("tz"));
    const today = getTodayInTimeZone(timeZone);

    await ensureOccurrences(userId, today);
    const tasks = await loadTasks(userId);
    return NextResponse.json({ tasks, today, timeZone });
  } catch (err) {
    console.error("loadTasks failed", err);
    return NextResponse.json({ error: "Failed to load tasks" }, { status: 500 });
  }
}

// POST /api/tasks — create a task, or a recurring series when `repeat` is present
export async function POST(request: Request) {
  let userId: string;
  try { userId = await requireAuth(); }
  catch { return unauthorized(); }

  const parsed = parseTaskPayload((await request.json()) as unknown);
  if (!parsed.ok) {
    return NextResponse.json({ error: parsed.error }, { status: 400 });
  }
  const { task, repeat } = parsed.value;

  const plan = await getUserPlan(userId);
  const count = await countUserTasks(userId);
  if (count >= MAX_TASKS_PER_USER) {
    return NextResponse.json({ error: "TASK_LIMIT_REACHED", limit: MAX_TASKS_PER_USER }, { status: 403 });
  }

  const activeSeries = await countActiveSeries(userId);
  if (repeat && activeSeries >= MAX_SERIES_PER_USER) {
    return NextResponse.json({ error: "SERIES_LIMIT_REACHED", limit: MAX_SERIES_PER_USER }, { status: 403 });
  }
  if (plan === "free") {
    // Occurrences are generated by the system and do not spend the quota; a
    // series does, once, however many occurrences it produces.
    const used = (await countUserLooseTasks(userId)) + activeSeries;
    if (used >= FREE_TASK_LIMIT) {
      return NextResponse.json(
        { error: "FREE_PLAN_LIMIT:task_limit_reached", limit: FREE_TASK_LIMIT },
        { status: 403 }
      );
    }
  }

  try {
    if (repeat) {
      // Projects cannot repeat (rejected by the parser), so kind is task or reminder.
      const kind = task.kind === "reminder" ? "reminder" : "task";
      const seriesId = crypto.randomUUID();
      await insertSeries(userId, {
        id: seriesId,
        userId,
        kind,
        title: task.title,
        category: task.category,
        description: task.description,
        priority: task.priority,
        estimateMin: task.estimateMin,
        time: task.time ?? null,
        rule: ruleFromRepeat(repeat),
        startsOn: task.dueDate,
        endsOn: repeat.until ?? null,
        active: true
      });
      const timeZone = await resolveUserTimeZone(userId);
      await ensureOccurrences(userId, getTodayInTimeZone(timeZone));
      const tasks = await loadSeriesOccurrences(userId, seriesId);
      return NextResponse.json({ task: tasks[0] ?? null, tasks });
    }

    const created = await createTask(task, userId);
    return NextResponse.json({ task: created });
  } catch (err) {
    console.error("createTask failed", err);
    return NextResponse.json({ error: "Failed to create task" }, { status: 500 });
  }
}

// PUT /api/tasks — update a task.
//
// `scope: "following"` on an occurrence ends its series the day before and starts
// a new one from that date with the edited fields. The response then asks the
// client to reload, since many rows changed at once.
export async function PUT(request: Request) {
  let userId: string;
  try { userId = await requireAuth(); }
  catch { return unauthorized(); }

  const raw = (await request.json()) as unknown;
  const parsed = parseTaskPayload(raw);
  if (!parsed.ok) {
    return NextResponse.json({ error: parsed.error }, { status: 400 });
  }
  const { task } = parsed.value;
  const scope = parseScope((raw as { scope?: unknown }).scope);

  try {
    if (scope === "following") {
      if (task.kind === "project") {
        return NextResponse.json({ error: "A project cannot repeat" }, { status: 400 });
      }
      const changes: OccurrenceChanges = {
        title: task.title,
        category: task.category,
        description: task.description,
        priority: task.priority,
        estimateMin: task.estimateMin,
        time: task.time ?? null,
        kind: task.kind === "reminder" ? "reminder" : "task"
      };
      const result = await editFollowing(seriesStore, userId, task.id, changes, crypto.randomUUID());
      if (!result.ok) return followingFailure(result);

      const timeZone = await resolveUserTimeZone(userId);
      await ensureOccurrences(userId, getTodayInTimeZone(timeZone));
      return NextResponse.json({ reload: true });
    }

    const updated = await updateTask(task, userId);
    if (!updated) {
      return NextResponse.json({ error: "Task not found or cannot be changed" }, { status: 404 });
    }
    return NextResponse.json({ task: updated });
  } catch (err) {
    console.error("updateTask failed", err);
    return NextResponse.json({ error: "Failed to update task" }, { status: 500 });
  }
}

// PATCH /api/tasks — toggle done status
export async function PATCH(request: Request) {
  let userId: string;
  try { userId = await requireAuth(); }
  catch { return unauthorized(); }

  const body = (await request.json()) as { taskId?: string; done?: boolean };
  if (typeof body.taskId !== "string" || typeof body.done !== "boolean") {
    return NextResponse.json({ error: "Invalid request" }, { status: 400 });
  }

  try {
    const updated = await setTaskDone(body.taskId, body.done, userId);
    return NextResponse.json({ task: updated });
  } catch (err) {
    console.error("setTaskDone failed", err);
    return NextResponse.json({ error: "Failed to update task" }, { status: 500 });
  }
}

// DELETE /api/tasks?id=<taskId>&scope=this|following
//
// Deleting a single occurrence marks it skipped instead of removing the row:
// the missing date would fall inside the rolling window and be created again on
// the next load. `following` ends the series at that occurrence.
export async function DELETE(request: Request) {
  let userId: string;
  try { userId = await requireAuth(); }
  catch { return unauthorized(); }

  const { searchParams } = new URL(request.url);
  const taskId = searchParams.get("id");
  if (!taskId) {
    return NextResponse.json({ error: "Missing task id" }, { status: 400 });
  }
  const scope = parseScope(searchParams.get("scope"));

  try {
    if (scope === "following") {
      const result = await deleteFollowing(seriesStore, userId, taskId);
      if (!result.ok && result.reason === "not_found") return followingFailure(result);
      // A done or skipped occurrence cannot be a cut point: fall back to just it.
      if (result.ok) return NextResponse.json({ ok: true, reload: true });
    }

    // Loose tasks are not series rows, so the first call is a no-op for them.
    const wasOccurrence = await deleteOnlyThis(seriesStore, userId, taskId);
    if (!wasOccurrence) await deleteTaskById(taskId, userId);
    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error("deleteTaskById failed", err);
    return NextResponse.json({ error: "Failed to delete task" }, { status: 500 });
  }
}
